version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant # Use the desired version of Qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # Expose Qdrant's default port
    volumes:
      - qdrant_data:/qdrant/storage  # Persistent storage for Qdrant

  app:
    build:
      context: .  # Use the Dockerfile in the current directory
    container_name: fastapi_app
    ports:
      - "8080:8080"  # Map the app's port to the host
    depends_on:
      - qdrant  # Ensure Qdrant starts before this container
    volumes:
      - .:/app  # Mount the local app directory for development (optional)

volumes:
  qdrant_data:
